#!/usr/bin/env python
"""Re-pin the derived hashes in RELEASE-MANIFEST.json from their regenerated sources.

SWS-CORRECTIVE-01 workstream 2 (R2). `RELEASE-MANIFEST.json` records the SHA-256 of a set of
tracked files, and nothing in the tree ever wrote those hashes: they were maintained by hand.
A pin that only a human can update is a pin that goes stale, and one did - the
`shell/BUILD-MANIFEST.txt` pin was last written at `27bfc848` and has been wrong on committed
bytes ever since two later commits landed a regenerated manifest beside it.

WHAT THIS IS NOT. This is not a "make the gate green" button, and it must never be used as
one. Refreshing an expected hash without regenerating the artifact it describes would hide
exactly the drift the gate exists to find. So:

  * Only paths listed in `generated_artifacts` - files that are DERIVED from other tracked
    content by a named generator - may be re-pinned. A hand-authored file's hash changing is
    a real finding, and `--write` refuses to paper over it.

  * Every derived path must pass its own generator's `--check` FIRST. If
    `shell/BUILD-MANIFEST.txt` does not describe the tree, this tool refuses to pin whatever
    it happens to contain; the manifest is regenerated by its own generator, and only then is
    the pin taken from it.

  * Every change is printed, with the old and new hash, so a diff of this file is reviewable.

Release procedure after changing anything under `shell/`:

    py -3.12 tools/release/generate_build_manifest.py --write
    py -3.12 tools/release/sync_release_manifest.py --write
    git add shell/BUILD-MANIFEST.txt RELEASE-MANIFEST.json    # committed together
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

_STAMP = re.compile(rb"^#\s*utc:\s*\S+\s*$", re.IGNORECASE)

#: Each derived path and the generator that owns it. A path may be re-pinned only after its
#: generator reports that the file describes the current tree.
GENERATORS = {
    "shell/BUILD-MANIFEST.txt": ["tools/release/generate_build_manifest.py", "--check"],
}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_content(path: Path) -> str:
    """Whole-file hash with generation-stamp lines removed - what the checker compares."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for line in handle:
            if _STAMP.match(line.rstrip(b"\r\n")):
                continue
            digest.update(line)
    return digest.hexdigest()


def generated_paths(manifest: dict) -> set[str]:
    declared = manifest.get("generated_artifacts") or {}
    paths = declared.get("paths") if isinstance(declared, dict) else declared
    return {str(p).replace("\\", "/") for p in (paths or [])}


def repin(args) -> int:
    """Re-pin a named hand-authored file, once, with a stated reason.

    `--write` only touches DERIVED artifacts, because a hand-authored file's hash changing is a
    real finding. But a hand-authored release input does sometimes change on purpose - a
    launcher is rewritten, a document is corrected - and the pin has to follow. That is a
    deliberate act, so it is spelled out: one path at a time, a reason on the command line, the
    old and new hash printed. What it is not is a way to make an unexplained mismatch disappear.
    """
    if not args.reason or not args.reason.strip():
        print("sync_release_manifest: --repin requires --reason. State why the file changed.")
        return 2
    reason_text = args.reason.strip()
    trivial = {"green", "fix", "update", "ci", "pass", "ok", "n/a", "none", "re-pin", "repin"}
    if len(reason_text) < 16 or reason_text.lower() in trivial:
        print("sync_release_manifest: --reason must describe the reviewed content change "
              "(at least 16 characters; not a gate-greening placeholder).")
        return 2

    root = repo_root()
    manifest_path = root / "RELEASE-MANIFEST.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    derived = generated_paths(manifest)
    wanted = {p.replace("\\", "/") for p in args.repin}

    pins = []
    def walk(node):
        if isinstance(node, dict):
            path = str(node.get("path") or "").replace("\\", "/")
            if path and "sha256" in node:
                pins.append(node)
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)
    walk(manifest)

    changed = False
    for path in sorted(wanted):
        if path in derived:
            print("sync_release_manifest: {} is a derived artifact; use --write so its "
                  "generator vouches for it.".format(path))
            return 1
        matching = [item for item in pins
                    if str(item.get("path") or "").replace("\\", "/") == path]
        if not matching:
            print("sync_release_manifest: {} is not pinned".format(path))
            return 1
        full = root / path
        if not full.is_file():
            print("sync_release_manifest: {} does not exist".format(path))
            return 1
        measured = sha256_file(full)
        any_change = False
        for item in matching:
            if measured == item.get("sha256"):
                continue
            reason = args.reason.strip()
            now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
            was = item.get("sha256")
            print("re-pinning {}\n  was      {}\n  now      {}\n  reason   {}".format(
                path, was, measured, reason))
            item["sha256"] = measured
            # F-070: persist WHY the expected hash was refreshed. Printing the reason left no durable
            # record in RELEASE-MANIFEST.json, so a later reader could not tell an authorized re-pin
            # from one done merely to make a check green (directive Section 2). Stamp the item and
            # append a repin_history entry.
            item["repin_reason"] = reason
            item["repin_utc"] = now
            manifest.setdefault("repin_history", []).append({
                "path": path, "was": was, "now": measured, "reason": reason, "utc": now,
            })
            any_change = True
            changed = True
        if not any_change:
            print("sync_release_manifest: {} already matches its pin".format(path))

    if changed:
        manifest_path.write_text(json.dumps(manifest, indent=2) + "\n",
                                 encoding="utf-8", newline="\n")
        print("sync_release_manifest: {} written".format(manifest_path.name))
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true",
                       help="report derived pins that are stale, change nothing")
    group.add_argument("--write", action="store_true",
                       help="re-pin the derived hashes, after their generators agree")
    group.add_argument("--repin", metavar="PATH", action="append",
                       help="re-pin ONE hand-authored file whose content you changed on "
                            "purpose. Requires --reason. Never use this to clear a gate you "
                            "did not intend to change.")
    parser.add_argument("--reason", help="why the named file's content changed (required "
                                         "with --repin; recorded in this run's output)")
    args = parser.parse_args(argv)

    if args.repin:
        return repin(args)

    root = repo_root()
    manifest_path = root / "RELEASE-MANIFEST.json"
    raw = manifest_path.read_text(encoding="utf-8")
    manifest = json.loads(raw)
    derived = generated_paths(manifest)

    changes = []
    for item in manifest.get("batch_files", []):
        path = str(item.get("path") or "").replace("\\", "/")
        if path not in derived:
            continue
        full = root / path
        if not full.is_file():
            print("sync_release_manifest: FAIL - derived artifact missing: {}".format(path))
            return 1
        measured = sha256_content(full)
        if measured != item.get("sha256"):
            changes.append((path, item.get("sha256"), measured, item))

    if not changes:
        print("sync_release_manifest: PASS - every derived pin already matches its artifact")
        return 0

    print("sync_release_manifest: {} derived pin(s) differ from their artifacts:".format(
        len(changes)))
    for path, old, new, _ in changes:
        print("  {}\n    pinned   {}\n    measured {}".format(path, old, new))

    if args.check:
        print("  Re-pin with: py -3.12 tools/release/sync_release_manifest.py --write")
        return 1

    # --write: each generator must vouch for its artifact before its pin is taken from it.
    for path, _old, _new, _item in changes:
        command = GENERATORS.get(path)
        if not command:
            print("sync_release_manifest: REFUSED - {} is declared generated but no generator "
                  "is registered for it. Register one rather than pinning whatever the file "
                  "currently holds.".format(path))
            return 1
        proc = subprocess.run([sys.executable, str(root / command[0])] + command[1:],
                              capture_output=True, text=True)
        if proc.returncode != 0:
            print("sync_release_manifest: REFUSED - {} does not describe this tree, so its "
                  "hash must not be pinned. Regenerate it first.".format(path))
            print(proc.stdout.rstrip())
            return 1
        print("  generator vouches for {}".format(path))

    for path, old, new, item in changes:
        item["sha256"] = new
        print("  re-pinned {}: {} -> {}".format(path, old, new))

    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n",
                             encoding="utf-8", newline="\n")
    print("sync_release_manifest: {} written".format(manifest_path.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
