"""EPC-01 P2-1/P2-2/P2-3 - the SBOM must describe the product, not the build machine.

The previous SBOM was generated by walking the build host's virtual environments and
`node_modules`. Three consequences, all measured before this test was written:

  * 173 of its 477 entries were `file` components - individual files scraped out of a
    `.venv`. A file is not a licensable component, and no recipient receives those paths.
  * Its own metadata declared Python coverage *partial*, because a venv only holds what
    that host happened to have installed.
  * It listed **62 packages the product does not contain**. They were transitive
    dependencies of `@electron/get@2.0.3` while the lock pins `5.1.0`; the SBOM carried
    both trees. Over-reporting is not the safe direction of error - a vulnerability
    scanner fed those names raises findings against software that is not there.

`tools/release/generate_sbom.py` reads the six lock files instead, and records each one's
path and SHA-256 so the provenance can be checked rather than believed. These tests hold
the properties that make the result worth anything.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SBOM = REPO_ROOT / "SBOM.json"
TOOL = REPO_ROOT / "tools" / "release" / "generate_sbom.py"


def _sbom() -> dict:
    return json.loads(SBOM.read_text(encoding="utf-8"))


def _meta_properties(document: dict) -> dict[str, str]:
    component = document["metadata"]["component"]
    return {p["name"]: p["value"] for p in component.get("properties", [])}


class SbomIsGeneratedFromLocks(unittest.TestCase):

    def setUp(self) -> None:
        self.assertTrue(SBOM.is_file(), "SBOM.json is missing")
        self.assertTrue(TOOL.is_file(), "tools/release/generate_sbom.py is missing")
        self.sbom = _sbom()

    def test_no_component_is_a_file_scraped_from_a_virtual_environment(self) -> None:
        files = [c for c in self.sbom["components"] if c.get("type") == "file"]
        self.assertEqual(
            files, [],
            f"{len(files)} file-type components are present; the SBOM is describing the "
            f"build host's disk rather than the product's dependencies"
        )

    def test_every_component_declares_a_licence(self) -> None:
        """The NOTICE is generated from this file. A silent gap here ships as a gap there."""
        missing = [
            f"{c['name']}@{c.get('version')}"
            for c in self.sbom["components"]
            if not c.get("licenses")
        ]
        self.assertEqual(missing, [], f"components without a licence: {missing[:10]}")

    def test_every_component_declares_whether_it_reaches_the_operator(self) -> None:
        """`required` vs `optional` is what separates shipped code from build-time tooling."""
        unscoped = [
            f"{c['name']}@{c.get('version')}"
            for c in self.sbom["components"]
            if c.get("scope") not in {"required", "optional"}
        ]
        self.assertEqual(unscoped, [], f"components without a scope: {unscoped[:10]}")

    def test_it_names_the_lock_files_it_was_generated_from_and_they_still_match(self) -> None:
        """Provenance that cannot be checked is decoration. This checks it."""
        sources = self.sbom.get("sovereign:sources")
        self.assertTrue(sources, "the SBOM does not record which lock files produced it")
        for source in sources:
            path = REPO_ROOT / source["path"]
            self.assertTrue(path.is_file(), f"declared lock source is missing: {source['path']}")
            actual = hashlib.sha256(path.read_bytes()).hexdigest()
            self.assertEqual(
                actual, source["sha256"],
                f"{source['path']} has changed since the SBOM was generated; "
                f"re-run tools/release/generate_sbom.py"
            )

    def test_it_does_not_leak_a_build_host_path(self) -> None:
        """The SBOM ships. An absolute path from the machine that cut it is developer
        identity in a customer-facing artifact, and means nothing on the recipient's disk."""
        raw = SBOM.read_text(encoding="utf-8")
        for needle in (":\\\\", ":/Users/", "C:\\\\", "/home/"):
            self.assertNotIn(
                needle, raw,
                f"SBOM.json contains {needle!r}, which looks like a build-host absolute path"
            )

    def test_modules_that_declare_no_dependencies_say_so_rather_than_being_omitted(self) -> None:
        """Three modules are stdlib-only. Silence would be indistinguishable from a miss."""
        declared = {m["module"] for m in self.sbom.get("sovereign:no_dependency_modules", [])}
        self.assertEqual(
            declared, {"distillery", "shell", "tokencenter"},
            "the set of modules declaring no dependencies has changed; if a module gained a "
            "dependency file it must appear in sovereign:sources instead"
        )

    def test_it_records_the_commit_it_was_cut_from(self) -> None:
        commit = _meta_properties(self.sbom).get("sovereign:source-commit")
        self.assertIsNotNone(commit, "the SBOM does not say which commit it describes")
        self.assertRegex(commit, r"^[0-9a-f]{40}$")

    def test_coverage_is_not_declared_partial(self) -> None:
        """The old SBOM marked its own Python coverage partial. That is honest, and it is
        also the defect. Generating from locks is what removes the caveat."""
        properties = _meta_properties(self.sbom)
        for key in ("sovereign:python-coverage", "sovereign:node-coverage"):
            self.assertEqual(
                properties.get(key), "complete-from-locks",
                f"{key} is {properties.get(key)!r}; the SBOM is not fully lock-derived"
            )

    def test_check_mode_agrees_the_committed_sbom_is_current(self) -> None:
        """The build calls this. If it passes here and fails there, the guard is worthless."""
        result = subprocess.run(
            [sys.executable, str(TOOL), "--check"],
            capture_output=True, text=True, timeout=900, cwd=str(REPO_ROOT),
        )
        self.assertEqual(
            result.returncode, 0,
            "SBOM.json is out of date with its lock files:\n"
            + (result.stdout + result.stderr)[-2000:]
        )


if __name__ == "__main__":
    unittest.main()
