"""Back up, verify and restore SOVEREIGN's external state home (SW-25).

    python -m sovereign_product.state_admin --root <install root> status
    python -m sovereign_product.state_admin --root <install root> backup --out <file.zip>
    python -m sovereign_product.state_admin --root <install root> verify --archive <file.zip>
    python -m sovereign_product.state_admin --root <install root> restore --archive <file.zip>

Stdlib only, so it runs before (or without) the product venv.

**Backup** writes a zip holding ``BACKUP_MANIFEST.json`` plus every state file under ``state/``.
The SQLite database is copied through the sqlite3 online-backup API, so the snapshot is consistent
even if the product is running; its ``-wal``/``-shm`` side files are therefore not copied.
Supervisor secrets (``api_key``, ``consumer.env``), pid files, locks and migration staging are
excluded: secrets are regenerated by the supervisor on first start, and pid/lock files describe
processes that will not exist when the backup is restored.

**Restore** refuses an archive whose manifest is missing or malformed, whose files do not match
their recorded sha256, which contains a path that escapes ``state/``, or whose state schema is
newer than this build supports. It extracts into a sibling staging directory, verifies it, then
swaps it in with two renames; the replaced state home is kept beside it as
``<home>.pre-restore-<utc>`` (never deleted) so a restore can itself be undone. Stop the workspace
first: a running product or shell holds files in the state home open and the swap will be refused.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sqlite3
import sys
import tempfile
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any

from .paths import resolve_state_home
from .state_migration import (
    STATE_SCHEMA,
    STATE_VERSION_FILE,
    StateVersionError,
    read_state_version,
)

BACKUP_MANIFEST = "BACKUP_MANIFEST.json"
BACKUP_KIND = "sovereign-state-backup"
BACKUP_SCHEMA = 1
STATE_PREFIX = "state/"
SQLITE_SUFFIXES = (".db", ".sqlite", ".sqlite3")
EXCLUDED_NAMES = {"api_key", "consumer.env", ".migration.lock", "watch.pid", "watch.spawn.lock"}
EXCLUDED_SUFFIXES = (".pid", ".lock", ".tmp", "-wal", "-shm", "-journal")
EXCLUDED_DIRS = {".migration-staging"}


class StateAdminError(RuntimeError):
    """A backup or restore was refused; nothing was changed."""


def _utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _excluded(relative: PurePosixPath) -> bool:
    if any(part in EXCLUDED_DIRS for part in relative.parts[:-1]):
        return True
    name = relative.name
    return name in EXCLUDED_NAMES or name.endswith(EXCLUDED_SUFFIXES)


def _is_sqlite(path: Path) -> bool:
    if not path.name.endswith(SQLITE_SUFFIXES):
        return False
    try:
        with path.open("rb") as handle:
            return handle.read(16) == b"SQLite format 3\x00"
    except OSError:
        return False


def _snapshot_sqlite(source: Path, target: Path) -> None:
    src = sqlite3.connect(f"file:{source.as_posix()}?mode=ro", uri=True)
    try:
        dst = sqlite3.connect(str(target))
        try:
            src.backup(dst)
        finally:
            dst.close()
    finally:
        src.close()


def status(root: str | os.PathLike[str] | Path) -> dict[str, Any]:
    home = resolve_state_home(Path(root))
    files = [p for p in home.rglob("*") if p.is_file()] if home.is_dir() else []
    return {
        "state_home": str(home),
        "exists": home.is_dir(),
        "state_version": read_state_version(home) if home.is_dir() else None,
        "supported_schema": STATE_SCHEMA,
        "files": len(files),
        "bytes": sum(p.stat().st_size for p in files),
    }


def backup(root: str | os.PathLike[str] | Path, out: str | os.PathLike[str] | Path) -> dict[str, Any]:
    """Write a verified backup archive of the state home to ``out`` (refuses to overwrite)."""

    from sovereign_version import PRODUCT_VERSION

    home = resolve_state_home(Path(root))
    if not home.is_dir():
        raise StateAdminError(f"no state home to back up at {home}")
    target = Path(out).expanduser().resolve()
    if target.exists():
        raise StateAdminError(f"refusing to overwrite an existing file: {target}")
    if target.is_relative_to(home.resolve()):
        raise StateAdminError("the backup archive may not be written inside the state home")
    version = read_state_version(home)
    entries: list[dict[str, Any]] = []
    target.parent.mkdir(parents=True, exist_ok=True)
    partial = target.with_name(f".{target.name}.{uuid.uuid4().hex}.partial")
    with tempfile.TemporaryDirectory(prefix="sovereign-backup-") as scratch:
        try:
            with zipfile.ZipFile(partial, "w", compression=zipfile.ZIP_DEFLATED) as archive:
                for path in sorted(home.rglob("*")):
                    if not path.is_file():
                        continue
                    relative = PurePosixPath(path.relative_to(home).as_posix())
                    if _excluded(relative):
                        continue
                    source = path
                    if _is_sqlite(path):
                        source = Path(scratch) / f"{uuid.uuid4().hex}.db"
                        _snapshot_sqlite(path, source)
                    archive.write(source, STATE_PREFIX + relative.as_posix())
                    entries.append({"path": relative.as_posix(), "sha256": _sha256_file(source),
                                    "size": source.stat().st_size})
                manifest = {
                    "schema": BACKUP_SCHEMA,
                    "kind": BACKUP_KIND,
                    "created_utc": _utc_now(),
                    "product_version": PRODUCT_VERSION,
                    "state_schema": (version or {}).get("schema", STATE_SCHEMA),
                    "files": entries,
                }
                archive.writestr(BACKUP_MANIFEST, json.dumps(manifest, indent=2, sort_keys=True))
            verify(partial)
            os.replace(partial, target)
        finally:
            if partial.exists():
                partial.unlink()
    return {"archive": str(target), "files": len(entries),
            "bytes": sum(e["size"] for e in entries), "state_schema": manifest["state_schema"]}


def _safe_member(name: str) -> PurePosixPath:
    if not name.startswith(STATE_PREFIX) or "\\" in name:
        raise StateAdminError(f"archive member outside {STATE_PREFIX}: {name!r}")
    relative = PurePosixPath(name[len(STATE_PREFIX):])
    if (not relative.parts or relative.is_absolute()
            or any(part in ("", ".", "..") or ":" in part for part in relative.parts)):
        raise StateAdminError(f"unsafe archive member: {name!r}")
    return relative


def verify(archive_path: str | os.PathLike[str] | Path) -> dict[str, Any]:
    """Check an archive's manifest, member paths and every file hash. Raises StateAdminError."""

    path = Path(archive_path)
    try:
        archive = zipfile.ZipFile(path)
    except (OSError, zipfile.BadZipFile) as exc:
        raise StateAdminError(f"not a readable backup archive: {exc}") from exc
    with archive:
        try:
            manifest = json.loads(archive.read(BACKUP_MANIFEST))
        except (KeyError, ValueError) as exc:
            raise StateAdminError(f"backup has no valid {BACKUP_MANIFEST}") from exc
        if (not isinstance(manifest, dict) or manifest.get("kind") != BACKUP_KIND
                or manifest.get("schema") != BACKUP_SCHEMA
                or not isinstance(manifest.get("files"), list)
                or not isinstance(manifest.get("state_schema"), int)):
            raise StateAdminError("backup manifest is not a sovereign state backup")
        if manifest["state_schema"] > STATE_SCHEMA:
            raise StateAdminError(
                f"backup state schema {manifest['state_schema']} is newer than this build "
                f"supports ({STATE_SCHEMA}); restore it with the release that made it")
        recorded = {}
        for entry in manifest["files"]:
            if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
                raise StateAdminError("backup manifest has a malformed file entry")
            _safe_member(STATE_PREFIX + entry["path"])
            recorded[STATE_PREFIX + entry["path"]] = entry.get("sha256")
        members = {info.filename for info in archive.infolist() if not info.is_dir()}
        members.discard(BACKUP_MANIFEST)
        for name in members:
            _safe_member(name)
        if members != set(recorded):
            extra = sorted(members - set(recorded))
            missing = sorted(set(recorded) - members)
            raise StateAdminError(f"backup contents disagree with its manifest "
                                  f"(unlisted: {extra[:5]}, missing: {missing[:5]})")
        for name, expected in recorded.items():
            if hashlib.sha256(archive.read(name)).hexdigest() != expected:
                raise StateAdminError(f"backup file hash mismatch: {name}")
    return manifest


def restore(root: str | os.PathLike[str] | Path,
            archive_path: str | os.PathLike[str] | Path) -> dict[str, Any]:
    """Replace the state home with a verified backup; the old home is kept, never deleted."""

    home = resolve_state_home(Path(root))
    if home == Path(root).expanduser().resolve():
        raise StateAdminError("this install keeps state in the install tree; nothing to restore into")
    manifest = verify(archive_path)
    stamp = _utc_stamp()
    staging = home.with_name(f"{home.name}.restoring-{uuid.uuid4().hex[:8]}")
    kept = home.with_name(f"{home.name}.pre-restore-{stamp}")
    staging.mkdir(parents=True)
    try:
        with zipfile.ZipFile(archive_path) as archive:
            for entry in manifest["files"]:
                relative = _safe_member(STATE_PREFIX + entry["path"])
                destination = staging.joinpath(*relative.parts)
                destination.parent.mkdir(parents=True, exist_ok=True)
                with archive.open(STATE_PREFIX + entry["path"]) as src, destination.open("wb") as dst:
                    shutil.copyfileobj(src, dst)
                if _sha256_file(destination) != entry["sha256"]:
                    raise StateAdminError(f"restored file hash mismatch: {entry['path']}")
        try:
            version = read_state_version(staging)
        except StateVersionError as exc:
            raise StateAdminError(str(exc)) from exc
        if version is not None and version["schema"] > STATE_SCHEMA:
            raise StateAdminError("restored state is newer than this build supports")
        if home.exists():
            try:
                os.replace(home, kept)
            except OSError as exc:
                raise StateAdminError(
                    f"could not move the current state home aside ({exc}); stop the workspace "
                    "(product, shell, supervisor) and retry") from exc
        os.replace(staging, home)
    except BaseException:
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)
        raise
    return {"restored_to": str(home), "previous_state_kept_at": str(kept) if kept.exists() else None,
            "files": len(manifest["files"]), "backup_created_utc": manifest.get("created_utc"),
            "backup_product_version": manifest.get("product_version")}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m sovereign_product.state_admin",
                                     description=__doc__.splitlines()[0])
    parser.add_argument("--root", required=True, help="the SOVEREIGN install root")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("status")
    b = sub.add_parser("backup")
    b.add_argument("--out", required=True)
    v = sub.add_parser("verify")
    v.add_argument("--archive", required=True)
    r = sub.add_parser("restore")
    r.add_argument("--archive", required=True)
    args = parser.parse_args(argv)
    try:
        if args.command == "status":
            result: Any = status(args.root)
        elif args.command == "backup":
            result = backup(args.root, args.out)
        elif args.command == "verify":
            manifest = verify(args.archive)
            result = {"ok": True, "files": len(manifest["files"]),
                      "state_schema": manifest["state_schema"],
                      "created_utc": manifest.get("created_utc")}
        else:
            result = restore(args.root, args.archive)
    except (StateAdminError, StateVersionError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}), file=sys.stderr)
        return 2
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
